# workflow name
name: blog to aliyun

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository master branch
              uses: actions/checkout@master
            - name: setup aliyun oss
              uses: manyuanrong/setup-ossutil@master
              with:
                  endpoint: oss-cn-beijing.aliyuncs.com
                  access-key-id: ${{ secrets.KEY }} # 刚刚配置过的AccessKeyId
                  access-key-secret: ${{ secrets.SECRET }} # 刚刚配置过的AccessKeySecret
            - name: cp files to aliyun
              run: ossutil cp -rf ./ oss://soto-blog/ # 将xxxxx改为创建的Bucket名称，-rf表示覆盖

